In [15]:
%config IPCompleter.use_jedi = False
import pandas as pd

In [16]:
engine_df = pd.read_csv('../data/engines.csv')
events_df = pd.read_csv('../data/events.csv')
findings_df = pd.read_csv('../data/Findings.csv')
aircraft_df = pd.read_csv('../data/aircraft.csv')
injury_df = pd.read_csv('../data/injury.csv')

In [17]:
corvair = 'CORVAIR'
eng_mfgr = 'eng_mfgr'
eng_model = 'eng_model'
corvair_mfr = engine_df[eng_mfgr].str.contains(corvair, False)
corvair_model = engine_df[eng_model].str.contains(corvair, False)
# corvair_mfr.head()
engine_df = engine_df[corvair_mfr | corvair_model]

In [18]:
df = pd.merge(events_df, engine_df, on='ev_id')
df = pd.merge(df, findings_df, on='ev_id')
df = pd.merge(df, aircraft_df, on='ev_id')
# df = pd.merge(df, injury_df, on='ev_id')

/var/folders/m_/0wm5dmjd5r57_p7zhbt9h9gm0000gn/T/ipykernel_9578/3548515776.py:3: FutureWarning: Passing 'suffixes' which cause duplicate columns {'lchg_userid_x', 'lchg_date_x'} in the result is deprecated and will raise a MergeError in a future version.
  df = pd.merge(df, aircraft_df, on='ev_id')

In [19]:
df

,ev_id,ntsb_no_x,ev_type,ev_date,ev_dow,ev_time,ev_tmzn,ev_city,ev_state,ev_country,...,acft_year,fuel_on_board,commercial_space_flight,unmanned,ifr_equipped_cert,elt_mounted_aircraft,elt_connected_antenna,elt_manufacturer,elt_model,elt_reason_other
0,20170924X05410,GAA17CA552,ACC,09/21/17 00:00:00,Th,1410.0,EDT,Franklin,PA,USA,...,1986.0,NaN,0,0,0,0,0,NaN,NaN,NaN
1,20170924X05410,GAA17CA552,ACC,09/21/17 00:00:00,Th,1410.0,EDT,Franklin,PA,USA,...,1986.0,NaN,0,0,0,0,0,NaN,NaN,NaN
2,20170326X54753,GAA17CA208,ACC,03/25/17 00:00:00,Sa,1530.0,EDT,Louisa,VA,USA,...,2014.0,NaN,0,0,0,0,0,NaN,NaN,NaN
3,20170326X54753,GAA17CA208,ACC,03/25/17 00:00:00,Sa,1530.0,EDT,Louisa,VA,USA,...,2014.0,NaN,0,0,0,0,0,NaN,NaN,NaN
4,20170326X54753,GAA17CA208,ACC,03/25/17 00:00:00,Sa,1530.0,EDT,Louisa,VA,USA,...,2014.0,NaN,0,0,0,0,0,NaN,NaN,NaN
5,20140923X13605,CEN14CA514,ACC,09/14/14 00:00:00,Su,1430.0,CDT,Fremont,NE,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
6,20140923X13605,CEN14CA514,ACC,09/14/14 00:00:00,Su,1430.0,CDT,Fremont,NE,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
7,20140923X13605,CEN14CA514,ACC,09/14/14 00:00:00,Su,1430.0,CDT,Fremont,NE,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
8,20091101X35012,WPR10LA039,ACC,10/30/09 00:00:00,Fr,1130.0,MST,Glendale,AZ,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
9,20091101X35012,WPR10LA039,ACC,10/30/09 00:00:00,Fr,1130.0,MST,Glendale,AZ,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
10,20091101X35012,WPR10LA039,ACC,10/30/09 00:00:00,Fr,1130.0,MST,Glendale,AZ,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
11,20140428X95502,ERA14CA210,ACC,04/27/14 00:00:00,Su,1130.0,EDT,Sumter,SC,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
12,20140428X95502,ERA14CA210,ACC,04/27/14 00:00:00,Su,1130.0,EDT,Sumter,SC,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
13,20140428X95502,ERA14CA210,ACC,04/27/14 00:00:00,Su,1130.0,EDT,Sumter,SC,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
14,20140428X95502,ERA14CA210,ACC,04/27/14 00:00:00,Su,1130.0,EDT,Sumter,SC,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
15,20090404X04529,ERA09LA231,ACC,04/04/09 00:00:00,Sa,1848.0,EDT,Valdosta,GA,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
16,20080923X01519,SEA08LA190,ACC,08/29/08 00:00:00,Fr,1230.0,PDT,Coeur d'Alene,ID,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
17,20080923X01519,SEA08LA190,ACC,08/29/08 00:00:00,Fr,1230.0,PDT,Coeur d'Alene,ID,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
18,20080923X01519,SEA08LA190,ACC,08/29/08 00:00:00,Fr,1230.0,PDT,Coeur d'Alene,ID,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
19,20080923X01519,SEA08LA190,ACC,08/29/08 00:00:00,Fr,1230.0,PDT,Coeur d'Alene,ID,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
20,20161204X04942,CEN17FA046,ACC,12/02/16 00:00:00,Fr,1237.0,CST,Mt Vernon,IN,USA,...,2007.0,NaN,0,0,0,0,0,NaN,NaN,NaN
21,20161204X04942,CEN17FA046,ACC,12/02/16 00:00:00,Fr,1237.0,CST,Mt Vernon,IN,USA,...,2007.0,NaN,0,0,0,0,0,NaN,NaN,NaN
22,20161204X04942,CEN17FA046,ACC,12/02/16 00:00:00,Fr,1237.0,CST,Mt Vernon,IN,USA,...,2007.0,NaN,0,0,0,0,0,NaN,NaN,NaN
23,20161204X04942,CEN17FA046,ACC,12/02/16 00:00:00,Fr,1237.0,CST,Mt Vernon,IN,USA,...,2007.0,NaN,0,0,0,0,0,NaN,NaN,NaN
24,20161204X04942,CEN17FA046,ACC,12/02/16 00:00:00,Fr,1237.0,CST,Mt Vernon,IN,USA,...,2007.0,NaN,0,0,0,0,0,NaN,NaN,NaN
25,20141022X53453,CEN15LA023,ACC,10/21/14 00:00:00,Tu,1745.0,CDT,Mountain Home,AR,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
26,20180910X60852,CEN18LA385,ACC,09/10/18 00:00:00,Mo,845.0,CDT,Temple,TX,USA,...,2018.0,NaN,0,0,0,0,0,NaN,NaN,NaN
27,20120301X02918,ERA12CA198,ACC,03/01/12 00:00:00,Th,745.0,EST,Boca Raton,FL,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
28,20120301X02918,ERA12CA198,ACC,03/01/12 00:00:00,Th,745.0,EST,Boca Raton,FL,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
29,20170606X10749,ERA17TA196,ACC,05/29/17 00:00:00,Mo,1330.0,EDT,Sanford,NC,USA,...,2016.0,NaN,0,0,0,0,0,NaN,NaN,NaN
30,20170606X10749,ERA17TA196,ACC,05/29/17 00:00:00,Mo,1330.0,EDT,Sanford,NC,USA,...,2016.0,NaN,0,0,0,0,0,NaN,NaN,NaN
31,20170606X10749,ERA17TA196,ACC,05/29/17 00:00:00,Mo,1330.0,EDT,Sanford,NC,USA,...,2016.0,NaN,0,0,0,0,0,NaN,NaN,NaN
32,20110729X51713,CEN11LA527,ACC,07/22/11 00:00:00,Fr,830.0,EDT,Ashtabula,OH,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
33,20110729X51713,CEN11LA527,ACC,07/22/11 00:00:00,Fr,830.0,EDT,Ashtabula,OH,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
34,20110729X51713,CEN11LA527,ACC,07/22/11 00:00:00,Fr,830.0,EDT,Ashtabula,OH,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
35,20110729X51713,CEN11LA527,ACC,07/22/11 00:00:00,Fr,830.0,EDT,Ashtabula,OH,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
36,20110414X73824,WPR11LA199,ACC,04/14/11 00:00:00,Th,940.0,PDT,Winchester,CA,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
37,20110414X73824,WPR11LA199,ACC,04/14/11 00:00:00,Th,940.0,PDT,Winchester,CA,USA,...,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
38,20160425X75915,CEN16LA167,ACC,04/24/16 00:00:00,Su,945.0,CDT,Hempstead,TX,USA,...,2005.0,NaN,0,0,0,0,0,NaN,NaN,NaN
39,20160425X75915,CEN16LA167,ACC,04/24/16 00:00:00,Su,945.0,CDT,Hempstead,TX,USA,...,2005.0,NaN,0,0,0,0,0,NaN,NaN,NaN

In [20]:
df.to_csv('../out/out.csv')